pipeline:
  build:
    image: appleboy/golang-testing:${GO_VERSION}
    environment:
      - GOPATH=/go
    commands:
      - make install
      - coverage all

services:
  redis:
    image: redis:alpine

workspace:
  path: /go/src/github.com/appleboy/gorush

matrix:
  GO_VERSION:
    - 1.7.1
    - 1.6.3
