pipeline:
  build:
    image: appleboy/golang-testing:${GO_VERSION}
    environment:
      - GOPATH=/go
    commands:
      - make install
      - coverage all

  line:
    image: appleboy/drone-line
    pull: true
    to: u359650f919427b5229330c7205c47ee4
    when:
      status: [ success, failure ]

services:
  redis:
    image: redis:alpine

workspace:
  path: /go/src/github.com/appleboy/gorush

matrix:
  GO_VERSION:
    - 1.7.1
    - 1.6.3
