gorush:
  build: ./golang
  links:
    - redis
  privileged: true
  environment:
    - ANDROID_API_KEY
    - ANDROID_TEST_TOKEN
  volumes:
    - ../:/app
  command: /bin/sh -c './docker/testing.sh'

redis:
  build: ./redis
  privileged: true
