version: "2"

services:
  gorush:
    build:
      context: ./golang
      args:
        PROJECT_PATH: $PROJECT_PATH
    links:
      - redis
    privileged: true
    environment:
      - ANDROID_API_KEY
      - ANDROID_TEST_TOKEN
    volumes:
      - ../:$PROJECT_PATH
    command: /bin/sh -c './docker/testing.sh'

  redis:
    build: ./redis
    privileged: true
